### PR TITLE
Typos and few other additions...

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Notes ... 
- F' yeah, incrementally improve style sheet.
- The dashboard sounds like a lot of work.
- Widgets.... Look Robin, W3C widgets is not going to happen :)
- Yes, mailing list achieve is crappy. Wish it was mobile friendly at least. 
- OMG! We have to kill bugzilla. It's so literally awful. 
- Critic is awful (I've never used it because it's awful ... ok, I don't know if it's awful, but github's thing seems good enough :)).

**Comment by darobin** [comment]
The dashboard isn't that much work, and it is needed for people who have something to contribute but aren't full time. It's not a big deal to put it together.

Critic has a learning curve. It should only be used when you are reviewing things more complicated than GH supports. But sometimes you need that.

**Comment by marcoscaceres** [comment]
> Critic has a learning curve. It should only be used when you are reviewing things more complicated than GH supports. But sometimes you need that.

Honest question: like what? I've never run into a situation where what GH provides didn't do the job - so really interested to know what I've been missing out on.

**Comment by darobin** [comment]
My experience is that GH gets pretty clunky whenever there's a lot of code involved. Especially from different files. Or when you need to collaborate on stuff, like "you review the Python, I'll review the JS". (Note that I'm only considering case where it makes sense to have a large batch of changes, e.g. adding a feature to back and front ends).

If you have more than, say, three problems with a PR there's a point at which GH breaks down. You get this weird situation where you have a bunch of sub-threads mixed in the code but then also shown linearly in the discussion. If you want to know that someone has fixed the issue you had you need to page through it all. Critic manages those as separate issues that are easy to get to and are their own threads, and you know when you've accepted each and everyone of them.

Like I said, GH review is great for a lot of cases. Critic is great for when that breaks down.

The problem with Critic is the learning curve, and a bunch of usability paper cuts. They're moving towards a system where they have a sane API-based backend and a webapp frontend. That should help a lot.

But the point here is not to ram Critic down people's throats; just to make it available when needed.

**Comment by marcoscaceres** [comment]
@darobin ok, got it. Thanks for the clarifications!

**Pull request merged**
