### PR TITLE
Add a section for stakeholders.

### PR DESCRIPTION
**Pull request by tobie**

### CODE REVIEW

**Comment by darobin** [comment]
I think it's a good idea to include this, my only question is: who or what are "End Users"?

**Comment by tobie** [comment]
Yeah, I was lukewarm about adding "End Users". I mean people actually using the implementations to visit content created by authors.

**Comment by darobin** [comment]
I don't think they're stakeholders for W3C tooling, really.

**Comment by tripu** [comment]
I think it's good to have an explicit list of (types of) stakeholders. +1 to merge.

(ping @plehegar :)

**Pull request merged**
